#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use Cwd qw(chdir);
use v5.10;

chdir("$FindBin::Bin/client");

#print "now in $ENV{PWD} script in $FindBin::Bin\n";

our $retries = 0;
our $MAX_RETRIES = 5;
our $SLEEP_SECS = 10;

my @categories = ('Uncommon','Common','Rare','Super_Rare','Super_Rare?pagefrom=Ruk','Legendary', 'Away_Team_Missions', 'Space_Battle_Missions');

foreach (@categories) {
	downloadCategory($_);
}

say "Telling bot to restart";
system("pkill -F ../data/run.pid");

sub checkDownload {
	my ($path) = @_;
	my $size = (stat $path)[7];
	say "$path downloaded with size $size";
	# Here's the check we'll apply for badness
	return ($size > 10000);
}

sub downloadCategory {
	my ($cat) = @_;
	my $path = "stt.wiki/wiki/Category:$cat";
	say "Downloading $path";
	
	my $cmd = "wget -m -np -l1 -o$FindBin::Bin/logs/$cat.log https://stt.wiki/wiki/Category:$cat";
	system($cmd);
	
	if (!checkDownload($path)) {
		if ($retries < $MAX_RETRIES) {
			$retries ++;
			say "That looks corrupt so will retry ($retries) again soon";
			sleep($SLEEP_SECS); # Wait one minute
			# Tail recursion!
			goto &downloadCategory;
		}
		else {
			say "Maximum retries hit - bailing";
			exit 1;
		}

	}
}